// ─── Mock Data for UI-Only Mode ──────────────────────────────────────────────
// Used when VITE_API_URL is not set. Replace with real API when backend is ready.

import { BountyResponse, SubmissionResponse, WinnerResponse } from './client';

const now = Date.now();
const HOUR = 3600000;
const DAY = 86400000;

export const MOCK_TON_PRICE = 3.25;

export const MOCK_BOUNTIES: BountyResponse[] = [
  {
    id: 'bounty-1',
    escrowAddress: 'EQD2fG9c8vXn4kLpR7wT3mJ6sY1hA5bN0qE8iUoP9dF4gH7',
    title: 'Follow me on Twitter',
    description: 'Follow @bountyhive on Twitter and share a screenshot of the follow confirmation. First 100 followers win a share of the pool!',
    type: 'task',
    poolAmount: '1',
    poolUsd: '3.25',
    winnerCount: 100,
    perWinnerAmount: '0.01',
    perWinnerUsd: '0.0325',
    winnerSelection: 'draw',
    verification: 'manual',
    verificationRule: 'Screenshot of follow confirmation',
    status: 'active',
    duration: 24,
    platformFeeBps: 100,
    createdAt: new Date(now - 2 * HOUR).toISOString(),
    endsAt: new Date(now + 22 * HOUR).toISOString(),
    reviewEndsAt: new Date(now + 46 * HOUR).toISOString(),
    completedAt: null,
    ownerId: 'user-1',
    owner: { id: 'user-1', username: 'bountyhive', displayName: 'BountyHive', avatarUrl: null },
    submissions: [],
    winners: [],
    submissionCount: 23,
  },
  {
    id: 'bounty-2',
    escrowAddress: 'EQBa1c2D3e4F5g6H7i8J9k0L1m2N3o4P5q6R7s8T9u0V1w',
    title: 'Create a meme about TON',
    description: 'Create and share an original meme about TON blockchain. Funniest meme wins! Be creative and make us laugh. Submit your meme as a link to your post.',
    type: 'creative',
    poolAmount: '5',
    poolUsd: '16.25',
    winnerCount: 3,
    perWinnerAmount: '1.667',
    perWinnerUsd: '5.42',
    winnerSelection: 'manual',
    verification: 'manual',
    verificationRule: 'Original meme image or video link',
    status: 'active',
    duration: 24,
    platformFeeBps: 100,
    createdAt: new Date(now - 12 * HOUR).toISOString(),
    endsAt: new Date(now + 12 * HOUR).toISOString(),
    reviewEndsAt: new Date(now + 36 * HOUR).toISOString(),
    completedAt: null,
    ownerId: 'user-2',
    owner: { id: 'user-2', username: 'tonwhales', displayName: 'TON Whales', avatarUrl: null },
    submissions: [
      {
        id: 'sub-1',
        bountyId: 'bounty-2',
        userId: 'user-3',
        proofUrl: 'https://t.me/c/12345/567',
        status: 'pending',
        submittedAt: new Date(now - 1 * HOUR).toISOString(),
        reviewedAt: null,
        user: { id: 'user-3', username: 'memelord', displayName: 'Meme Lord', avatarUrl: null },
      },
    ],
    winners: [],
    submissionCount: 7,
  },
  {
    id: 'bounty-3',
    escrowAddress: 'EQCx4d5E6f7G8h9I0j1K2l3M4n5O6p7Q8r9S0t1U2v3W4x',
    title: 'Answer TON trivia quiz',
    description: 'Test your knowledge about TON blockchain! Answer 5 questions correctly to enter the prize draw. Questions cover TON history, technology, and ecosystem.',
    type: 'quiz',
    poolAmount: '2',
    poolUsd: '6.50',
    winnerCount: 10,
    perWinnerAmount: '0.2',
    perWinnerUsd: '0.65',
    winnerSelection: 'draw',
    verification: 'auto',
    verificationRule: 'All 5 answers must be correct',
    status: 'active',
    duration: 24,
    platformFeeBps: 100,
    createdAt: new Date(now - 18 * HOUR).toISOString(),
    endsAt: new Date(now + 6 * HOUR).toISOString(),
    reviewEndsAt: new Date(now + 30 * HOUR).toISOString(),
    completedAt: null,
    ownerId: 'user-1',
    owner: { id: 'user-1', username: 'bountyhive', displayName: 'BountyHive', avatarUrl: null },
    submissions: [],
    winners: [],
    submissionCount: 45,
  },
  {
    id: 'bounty-4',
    escrowAddress: 'EQDy6z7A8b9C0d1E2f3G4h5I6j7K8l9M0n1O2p3Q4r5S6t',
    title: 'Write a review of BountyHive',
    description: 'Write an honest review of the BountyHive platform and share it on social media. Best review wins! We value detailed, constructive feedback.',
    type: 'creative',
    poolAmount: '10',
    poolUsd: '32.50',
    winnerCount: 5,
    perWinnerAmount: '2',
    perWinnerUsd: '6.50',
    winnerSelection: 'manual',
    verification: 'manual',
    verificationRule: 'Link to published review',
    status: 'review',
    duration: 24,
    platformFeeBps: 100,
    createdAt: new Date(now - DAY - 4 * HOUR).toISOString(),
    endsAt: new Date(now - 4 * HOUR).toISOString(),
    reviewEndsAt: new Date(now + 20 * HOUR).toISOString(),
    completedAt: null,
    ownerId: 'user-4',
    owner: { id: 'user-4', username: 'bountyadmin', displayName: 'Bounty Admin', avatarUrl: null },
    submissions: [
      {
        id: 'sub-2',
        bountyId: 'bounty-4',
        userId: 'user-5',
        proofUrl: 'https://twitter.com/user5/status/123456',
        status: 'approved',
        submittedAt: new Date(now - 20 * HOUR).toISOString(),
        reviewedAt: new Date(now - 18 * HOUR).toISOString(),
        user: { id: 'user-5', username: 'cryptoreviewer', displayName: 'Crypto Reviewer', avatarUrl: null },
      },
      {
        id: 'sub-3',
        bountyId: 'bounty-4',
        userId: 'user-6',
        proofUrl: 'https://t.me/s/123456789',
        status: 'pending',
        submittedAt: new Date(now - 2 * HOUR).toISOString(),
        reviewedAt: null,
        user: { id: 'user-6', username: 'tonfan', displayName: 'TON Fan', avatarUrl: null },
      },
    ],
    winners: [
      {
        id: 'w-1',
        bountyId: 'bounty-4',
        userId: 'user-5',
        payoutAmount: '2',
        payoutTxHash: null,
        paidAt: null,
        user: { id: 'user-5', username: 'cryptoreviewer', displayName: 'Crypto Reviewer', avatarUrl: null },
      },
    ],
    submissionCount: 12,
  },
  {
    id: 'bounty-5',
    escrowAddress: null,
    title: 'Share our Telegram group',
    description: 'Share our Telegram group with 3 friends and screenshot the proof. Simple task, quick reward!',
    type: 'task',
    poolAmount: '0.5',
    poolUsd: '1.63',
    winnerCount: 50,
    perWinnerAmount: '0.01',
    perWinnerUsd: '0.0325',
    winnerSelection: 'draw',
    verification: 'auto',
    verificationRule: 'Screenshot of shared group link',
    status: 'completed',
    duration: 24,
    platformFeeBps: 100,
    createdAt: new Date(now - 3 * DAY).toISOString(),
    endsAt: new Date(now - DAY).toISOString(),
    reviewEndsAt: new Date(now - 12 * HOUR).toISOString(),
    completedAt: new Date(now - 12 * HOUR).toISOString(),
    ownerId: 'user-2',
    owner: { id: 'user-2', username: 'tonwhales', displayName: 'TON Whales', avatarUrl: null },
    submissions: [],
    winners: [],
    submissionCount: 50,
  },
  {
    id: 'bounty-6',
    escrowAddress: 'EQAz8B9c0D1e2F3g4H5i6J7k8L9m0N1o2P3q4R5s6T7u8V9w',
    title: 'Design a logo for TON Dogs',
    description: 'Design a creative logo for the TON Dogs NFT collection. The logo should be modern, fun, and recognizable. Submit your design as a PNG or SVG file link.',
    type: 'creative',
    poolAmount: '20',
    poolUsd: '65.00',
    winnerCount: 1,
    perWinnerAmount: '20',
    perWinnerUsd: '65.00',
    winnerSelection: 'manual',
    verification: 'manual',
    verificationRule: 'Original logo design file link',
    status: 'active',
    duration: 24,
    platformFeeBps: 100,
    createdAt: new Date(now - 6 * HOUR).toISOString(),
    endsAt: new Date(now + 18 * HOUR).toISOString(),
    reviewEndsAt: new Date(now + 42 * HOUR).toISOString(),
    completedAt: null,
    ownerId: 'user-7',
    owner: { id: 'user-7', username: 'tondogs', displayName: 'TON Dogs', avatarUrl: null },
    submissions: [],
    winners: [],
    submissionCount: 3,
  },
];

export const MOCK_TOKENS = [
  { address: 'EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c', symbol: 'TON', name: 'The Open Network', decimals: 9, priceUsd: 3.25 },
  { address: 'EQCxFRclYDjNjJ5pLJ6q2Y0gE0_VxJQ0jK0z0qL5l5l5l5', symbol: 'USDT', name: 'Tether USD', decimals: 6, priceUsd: 1.0 },
  { address: 'EQAvlWFDxg2la5-ToE3_SGKBODkbO4W5v5O4F0I0kE6_Y3', symbol: 'USDC', name: 'USD Coin', decimals: 6, priceUsd: 1.0 },
  { address: 'EQD0vdEA4Qj8x4l4Q8Rbt3fYg3vJ3g3vJ3g3vJ3g3vJ3g3v', symbol: 'NOT', name: 'Notcoin', decimals: 9, priceUsd: 0.01 },
  { address: 'EQCjkCxvcMDXsVoqQ8Qx1Wq0JN3g3vJ3g3vJ3g3vJ3g3vJ3', symbol: 'JUP', name: 'Jupiter', decimals: 9, priceUsd: 1.2 },
];
